### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by jason-hub** [patrickingle/mavis-https-to-http-redirect#4]
Hello, 

I am receiving the following error in my logs: 

`PHP Warning:  preg_match(): Unknown modifier 'w' in /.../wp-content/plugins/mavis-https-to-http-redirect/mavis.php on line 207, referer: https://.../writing/wp-cron.php?doing_wp_cron=1489732133.0911049842834472656250`

Please advise how to fix it.

Thank you!

**Comment by patrickingle** [comment]
Ok, will look into the issue

**Comment by patrickingle** [comment]
fixed in version 1.4.3
